### ISSUE TITLE
Testing - test load 19K sample bundles

### ISSUE THREAD

**Issue by briandoconnor** [HumanCellAtlas/data-bundle-examples#9] opened 2017-07-17 04:28 UTC
In the last sprint we only were able to load 22 sample bundles.  We're waiting a blue box fix.  But after this fix is in place, deploy a new system and load all of Jim's samples.

**Comment by kozbo** [comment] 2017-07-24 18:28
Is this a duplicate of #232?

**Comment by briandoconnor** [comment] 2017-08-02 17:49
@kozbo this was created as a new ticket since the last ticket only loaded 22 samples.

**Comment by briandoconnor** [comment] 2017-08-02 17:54
Need to check in with @sampierson, I think he's staged data in the new account, right?  But I don't think he's onboarded the 19K samples into a staging instance of the HCA storage system.

**Comment by briandoconnor** [comment] 2017-08-02 21:18
FYI, should update the manifest to include stable UUIDs

**Comment by kozbo** [comment] 2017-08-07 21:49
@sampierson are you blocked by [#234](https://github.com/HumanCellAtlas/data-store/issues/234)?

**Comment by sampierson** [comment] 2017-08-28 19:58
This is implemented and works for bundle with small files.  However the DSS API has now been made asynchronous for larger files and returns 202s, after which you are expected to poll your file repeatedly until it appears. `storer.py` needs to accommodate this new behavior.  I'll add that functionality this week.

**Comment by sampierson** [comment] 2017-09-08 19:09
The test was performed.  Some errors were produced which generated other ticket.

**Closed as completed by sampierson** 2017-09-08 19:09 UTC
